### ISSUE TITLE
Stacktrace appears launching a Server on Ubuntu 8.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#10]
```
Exception in thread "main" java.lang.UnsupportedOperationException
    at java.awt.TrayIcon.<init>(TrayIcon.java:120)
    at java.awt.TrayIcon.<init>(TrayIcon.java:144)
    at 
org.pierre.remotedroid.server.PRemoteDroidServerTrayIcon.initTrayIcon(PRemo
teDroidServerTrayIcon.java:124)
    at 
org.pierre.remotedroid.server.PRemoteDroidServerTrayIcon.<init>(PRemoteDroi
dServerTrayIcon.java:38)
    at 
org.pierre.remotedroid.server.PRemoteDroidServer.<init>(PRemoteDroidServer.
java:31)
    at 
org.pierre.remotedroid.server.PRemoteDroidServer.main(PRemoteDroidServer.ja
va:71)



```

Original issue reported on code.google.com by `JeanYves...@gmail.com` on 28 Feb 2010 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
Don't use the OpenJDK.
Use the official Java runtime by Sun.

sudo apt-get install sun-java6-jre
sudo apt-get remove openjdk*
```

Original comment by `pierredu...@gmail.com` on 1 Mar 2010 at 2:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `pierredu...@gmail.com` on 5 Mar 2010 at 2:22
- Changed state: **Fixed**
