### ISSUE TITLE
Cannot open bluecove.jar files.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#111]
```
as I get the message that bluetooth server is not working,i've tried to open 
the bluecove.jar files (also tried the renamed "snapshot" files), but i get 
some error saying, "failed to load bluecove.jar"

I have installed Bluesoleil 6 as a bluetooth driver on my Windows 7 x64 pc.

DEBUGGER SAYS: 

java.net.BindException: Address already in use: JVM_Bind
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.PlainSocketImpl.bind(Unknown Source)
        at java.net.ServerSocket.bind(Unknown Source)
        at java.net.ServerSocket.<init>(Unknown Source)
        at java.net.ServerSocket.<init>(Unknown Source)
        at org.pierre.remotedroid.server.connection.PRemoteDroidServerTcp.<init>
(PRemoteDroidServerTcp.java:19)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDro
idServerApp.java:33)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroid
ServerApp.java:96)
Exception in thread "main" java.lang.NoClassDefFoundError: javax/microedition/io
/Connector
        at org.pierre.remotedroid.server.connection.PRemoteDroidServerBluetooth.
<init>(PRemoteDroidServerBluetooth.java:22)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDro
idServerApp.java:42)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroid
ServerApp.java:96)
Caused by: java.lang.ClassNotFoundException: javax.microedition.io.Connector
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more


Kindly help!!! (It is not said by the debugger :P )

```

Original issue reported on code.google.com by `yugandha...@gmail.com` on 3 Apr 2012 at 11:53

**Comment by GoogleCodeExporter** [comment]
```
Same Issue -.-
```

Original comment by `Dennis.H...@googlemail.com` on 2 Aug 2012 at 12:18

**Comment by GoogleCodeExporter** [comment]
```
two things 
1) change the blocove jar to x64 one. just replace old file with new x64 bit 
version from official site.
2) if 1 doesn't help then check if any other bluetooth application is running.
```

Original comment by `anant@anantshri.info` on 30 May 2013 at 6:17
