### ISSUE TITLE
Server crash using OpenJDK Java 6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#17]
```
What steps will reproduce the problem?
1. Start the server

What is the expected output? What do you see instead?
Expecting server running.
See:
Exception in thread "main" java.lang.UnsupportedOperationException
    at java.awt.TrayIcon.<init>(TrayIcon.java:120)
    at java.awt.TrayIcon.<init>(TrayIcon.java:144)
    at
org.pierre.remotedroid.server.gui.PRemoteDroidServerTrayIcon.initTrayIcon(PRemot
eDroidServerTrayIcon.java:185)
    at
org.pierre.remotedroid.server.gui.PRemoteDroidServerTrayIcon.<init>(PRemoteDroid
ServerTrayIcon.java:42)
    at
org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDroidServerApp
.java:29)
    at
org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroidServerApp.j
ava:96)


What version of the product are you using? On what operating system?
Ubuntu 9.10 and OpenJDK Java 6

```

Original issue reported on code.google.com by `Murphy2...@gmail.com` on 7 Mar 2010 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
Don't use OpenJDK
it doesn't support ray icon

please delete it and download the "official" java
sun-java6-jre package on debian/ubuntu
```

Original comment by `pierredu...@gmail.com` on 7 Mar 2010 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
Yep. This should be closed. ;)
```

Original comment by `milan.jaros` on 5 May 2010 at 7:28

**Comment by GoogleCodeExporter** [comment]
```
If so, you should note in the frontpage that your software does only work with 
the Sun 
JRE and not with OpenJDK.
```

Original comment by `Murphy2...@gmail.com` on 6 May 2010 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
Murphy2712 is correct.  Users should be informed of this up front.
```

Original comment by `Etha...@gmail.com` on 18 May 2010 at 12:34
