### ISSUE TITLE
Bluetooth connection refused

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#41]
```
What steps will reproduce the problem?
1. Launch the server
2. Check that it runs
3. Try to connect using Bluetooth

What is the expected output? What do you see instead?
It should connect, the MAC and password are correct. It says connection
refused. No log in debug mode on neither the droid nor the server

What version of the product are you using? On what operating system?
Using HTC Desire (Droid 2.1) and Win 7 32Bit

Please provide any additional information below.
How does the Bluetooth connection is engineered? what Bluetooth profile
does it use? Is there any setting to check?

Thanks.

```

Original issue reported on code.google.com by `baroukh....@gmail.com` on 11 May 2010 at 11:32

**Comment by GoogleCodeExporter** [comment]
```
run the server in debug mode (PRemoteDroid-Server-debug.exe)
no error message ?
```

Original comment by `pierredu...@gmail.com` on 13 May 2010 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
I tried that without success. By looking further, I found out that the Desire 
was
using a crappy Bluetooth stack and therefore was not supporting SPP correctly. I
believe this must the profile you use.

Though I had a try at Remote Droid and it work OK (except for the app to crash 
often)
so it must be possible to make it work.
```

Original comment by `baroukh....@gmail.com` on 13 May 2010 at 11:37

**Comment by GoogleCodeExporter** [comment]
```
Same problem for me
"connection refused" with .exe or debug.exe
Desire 2.1
No solution?
```

Original comment by `caillard...@gmail.com` on 19 May 2010 at 7:41

**Comment by GoogleCodeExporter** [comment]
```
Same probleme with HTC Hero 2.1 + windows 7
```

Original comment by `nicolas....@gmail.com` on 4 Jun 2010 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
There seems to be a problem on the bluetooth stack of the Android 2.1 version 
from
HTC (with senseUI). They use a different stack which has problems with SPP 
(Serial
Port Protocol)
http://en.wikipedia.org/wiki/Serial_Port_Profile#Serial_Port_Profile_.28SPP.29

Here are a few links that illustrate the problem:
* 
http://groups.google.com/group/android-developers/browse_thread/thread/e8c16aff1
10ebbd5
* http://code.google.com/p/android/issues/detail?id=8382
*
http://android.modaco.com/content/htc-desire-desire-modaco-com/307447/updating-t
he-buggy-bluetooth-stack-of-the-desire/
http://androidforums.com/support-troubleshooting-incredible/77281-bluetooth-stac
k-stripped-spp.html


I have submitted a ticket to HTC. After a few email exchanges they agreed to 
submit a
issue to their development team but I doubt this will be high priority,. I 
encourage
anyone having the problem to contact HTC. When we will be 1,000 they might do
something about it.
```

Original comment by `baroukh....@gmail.com` on 4 Jun 2010 at 1:26

**Comment by GoogleCodeExporter** [comment]
```
damn :(

i have only a Nexus One (2.1) and a HTC Hero (1.5)
```

Original comment by `pierredu...@gmail.com` on 6 Jun 2010 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
same probleme with htc legend and sensUI (Android 2.1)... the problem is I need 
the bluetooth to use it at work for presentations (wifi not available)
```

Original comment by `Floriane...@gmail.com` on 11 Jun 2010 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
hello!
I have the same problem (HTC desires 2.1 / Seven 32)
if I switch to 2.2 andoid problem was there chance to settle?
```

Original comment by `dreamo...@gmail.com` on 13 Jun 2010 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
They are suppose to update the Bluetooth stack on 2.2 so maybe...
```

Original comment by `baroukh....@gmail.com` on 13 Jun 2010 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
i don't know :(
i haven't test 2.2
```

Original comment by `pierredu...@gmail.com` on 13 Jun 2010 at 5:31

**Comment by GoogleCodeExporter** [comment]
```
Any solution for "HTC Desire" and "Bluetooth Conection"?.

Thanks for all.
```

Original comment by `Kyan...@gmail.com` on 16 Jun 2010 at 4:49

**Comment by GoogleCodeExporter** [comment]
```
Nope. Nothing yet. My ticket is still open at HTC customer service. I can only 
encourage you to request a support ticket on that issue. It will tell HTC that 
many users are impacted.
```

Original comment by `baroukh....@gmail.com` on 16 Jun 2010 at 4:58

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem whit both wifi and bluetooth..
```

Original comment by `kristian...@gmail.com` on 18 Jun 2010 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
kristian.linde, If you have connection refused with WiFi, it is more that 
likely that you are having another problem or a wrong config. This issue is 
only due to a feature gap in the Bluetooth stack of HTC SenseUI for Android 2.1
```

Original comment by `baroukh....@gmail.com` on 18 Jun 2010 at 10:04

**Comment by GoogleCodeExporter** [comment]
```
Hi, ive just downloaded and installed your application to my phone (samsun 
galaxy spica i5700, android 2.1) and laptop (lenovo y450, win7 64). the wifi 
connectivity worked fined but i cannot connect/use you application through 
bluetooth. is there any way i can use the application through bluetooth?

here is whats written on the debug:

java.io.EOFException
at java.io.DataInputStream.readByte(Unknown Source)
at 
org.pierre.remotedroid.protocol.action.PRemoteDroidAction.parse(PRemoteDroid.jav
a:23)
at 
org.pierre.remotedroid.protocol.PRremoteDroidConnection.receiveAction(PRemoteDro
idConnection.java:30)
at 
org.pierre.remotedroid.server.connection.PRemoteDroidServerConnection.run(PRemot
eDroidServerConnection.java:73)
at java.lang.Thread.run(Unknown Source)
```

Original comment by `jan.reyn...@gmail.com` on 20 Jun 2010 at 12:18

**Comment by GoogleCodeExporter** [comment]
```
Same here ... HTC Desire 2.1, connection refused.
```

Original comment by `ivo...@gmail.com` on 8 Jul 2010 at 8:29

**Comment by GoogleCodeExporter** [comment]
```
Same here, htc desire 2.1 connection refused. 

Sounds like the htc issue is only related to bluetooth spp, can it be changed 
to hid or implemented some other way ?
```

Original comment by `phl....@gmail.com` on 13 Jul 2010 at 4:06

**Comment by GoogleCodeExporter** [comment]
```
i don't know how to use bluetooth without spp :(
(and i have no time to improve PRemoteDroid atm, i'm working on a new app)
```

Original comment by `pierredu...@gmail.com` on 18 Jul 2010 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
I can pair HTC desire standard 2.1 with my MAC OSX 10.5.8 but can not connect, 
not at all. Can't browse the device and can't send anything from the phone to 
the mac. It just fails each time.
```

Original comment by `matthewp...@gmail.com` on 21 Jul 2010 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
bluetooth, paired devices same error:
connection refused
Device: Motorola Milestone, Android 2.1
```

Original comment by `sijos...@gmail.com` on 23 Aug 2010 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
getting "connection refused" over wifi connection aswell.

LG eve(droid 1.6)
```

Original comment by `littleve...@gmail.com` on 14 Sep 2010 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
Same problems. HTC Wildfire Android 2.1

bluetooth failed, wi-fi works great
```

Original comment by `bratinam...@gmail.com` on 18 Nov 2010 at 7:04

**Comment by GoogleCodeExporter** [comment]
```
Same here Wifi works great bluetooth failed on Windows 7 64bit / HTC Wildfire 
Android 2.1

```

Original comment by `k.rijps...@gmail.com` on 19 Nov 2010 at 11:10

**Comment by GoogleCodeExporter** [comment]
```
Same problems. Bluetooth failed on HTC desire 2.2/ window 7 64bit.
```

Original comment by `yingyot....@gmail.com` on 22 Nov 2010 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
In windows server part has to be replaced a library. Search for link to actual 
snapshot of bluecove.jar
```

Original comment by `ho.ahr...@gmail.com` on 22 Dec 2010 at 4:59

**Comment by GoogleCodeExporter** [comment]
```
Worked for me        SOLVE
unzip the PRemoteDroid-Server.zip in a new folder and
execute all the .jar's and exe's and now it works
hope it works guys ZTE blade 2.1 ....
```

Original comment by `fear.pe...@gmail.com` on 11 Feb 2011 at 6:03

**Comment by GoogleCodeExporter** [comment]
```
same here, i have wildfire ver 2.2 but connection is refused from my laptop 
when i try transfer files via bluetooth.  i have winodws 7 64 bits
```

Original comment by `plam...@gmail.com` on 3 May 2011 at 1:38

**Comment by GoogleCodeExporter** [comment]
```
I also have this problem on my HTC Desire with Android 2.2. Any solution?
```

Original comment by `bszabo...@gmail.com` on 30 Aug 2011 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem with my Xperia X10i
and it says bluetooth server is not running...
how can we fix this?
```

Original comment by `blackstr...@gmail.com` on 7 Jun 2012 at 2:27

**Comment by GoogleCodeExporter** [comment]
```
Same here, with my GS2 running ICS, bluetooth connexion to a ubuntu laptop 
fails even with the snapshots jar files...
```

Original comment by `etienne....@gmail.com` on 2 Sep 2012 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
In my own case, rebooting the phone seems to allow Bluetooth connection to 
succeed.

I was having the "Connection refused" problem when using Bluetooth on my HTC 
EVO 3D, immediately after installing PRemoteDroid. With debugging enabled on 
both server and phone, no informative error messages were produced.  I rebooted 
the phone, and when I restarted PRemoteDroid, it happily connected via 
Blutooth. I  am  typing this sentence via a bt connection.

```

Original comment by `jakna...@gmail.com` on 26 Sep 2012 at 5:32
