### ISSUE TITLE
Bluetooth Server is not running

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#45]
```
I can't get the Bluetooth server to run - when I start up debug server I get 
the following in the console:

Exception in thread "main" java.lang.UnsatisfiedLinkError: 
com.intel.bluetooth.BluetoothStackToshiba
.getLibraryVersion()I
        at com.intel.bluetooth.BluetoothStackToshiba.getLibraryVersion(Native Method)
        at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack(BlueCoveImpl.java:939)
        at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:482)
        at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:65)
        at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1020)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1018)
        at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1011)
        at com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnector.java:196)
        at com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:162)
        at javax.microedition.io.Connector.open(Connector.java:83)
        at org.pierre.remotedroid.server.connection.PRemoteDroidServerBluetooth.<init>(PRemoteDroidS
erverBluetooth.java:22)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDroidServerApp.java:42)

        at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroidServerApp.java:96)

----------------------------------------------------------------

I'm using Bluetooth Stack for Windows by Toshiba, Version v7.10.12(T).  Let me 
know if you need any other information.
```

Original issue reported on code.google.com by `Dean.P.T...@gmail.com` on 23 Jun 2010 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
I am running into the EXACT same issue.
```

Original comment by `kwmer...@gmail.com` on 20 Aug 2010 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
i use 64 bit ubuntu and the bluetooth server will not start.  I've had problems 
in the past with 64 bit distributions and bluetooth compatibility. are you guys 
using 64 bit windows 7?
```

Original comment by `thehyper...@gmail.com` on 27 Sep 2010 at 2:11

**Comment by GoogleCodeExporter** [comment]
```
No - using 32-bit Windows 7
```

Original comment by `Dean.P.T...@gmail.com` on 27 Sep 2010 at 2:13

**Comment by GoogleCodeExporter** [comment]
```
Windows XP SP3
```

Original comment by `kwmer...@gmail.com` on 27 Sep 2010 at 6:46

**Comment by GoogleCodeExporter** [comment]
```
same, ubuntu 10.04 32 bit and win 7 64
```

Original comment by `gareth7yo@gmail.com` on 2 Oct 2010 at 4:46

**Comment by GoogleCodeExporter** [comment]
```
I just reformatted my computer 2 weeks ago, and it's back to having the default 
Windows Bluetooh Stack driver on in, and the bluetooth premotedroid app works.  
I had similar results with another bluetooth app I had on my phone, so I think 
it was a problem with the Toshiba stack driver.
```

Original comment by `Dean.P.T...@gmail.com` on 3 Oct 2010 at 2:33

**Comment by GoogleCodeExporter** [comment]
```
same problem here. using ubuntu 10.04 64bit
```

Original comment by `miran.me...@gmail.com` on 23 Nov 2010 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
I agree. I have the same problem.  Anybody knows the solution??? With 
bluesoleil works, but you have to pay. The Toshiba Stack its free, or at least 
cheaper, because came in a little cd with my bluetooth usb.
```

Original comment by `rodanm...@gmail.com` on 4 Dec 2010 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
Hope this is helpful to others...

I was having the same problem as listed by others. I was able to get the 
Bluetooth server to start by launching the application via the file 
"PRemoteDroid-Server.jar" where the server files are located. I'll also note 
that I paired my devices first and had wifi working before successfully getting 
it to work on Bluetooth. However now it works great and I'm happy with this 
application.
```

Original comment by `conrad.k...@gmail.com` on 17 Jan 2011 at 9:00

**Comment by GoogleCodeExporter** [comment]
```
I got my bluetooth to work.
1> pair bluetooth(s)
2> run bluecove-gpl-2.1.0 (nothing will come up)
3> run PRemoteDroid-Server

it will say if you click on the icon and hit bluetooth that bluetooth is 
running if it is working

PROFIT!!

(ubuntu 10.04 64) intel 9643 wireless(or whatever that chip set is)
```

Original comment by `tomtomsw...@gmail.com` on 4 Feb 2011 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
My bluetooth server still isn't running. I am running windows 7 64. I am able 
to pair my bluetooths, but i cannot run bluecove-gpl-2.1.0 or the other 
bluecove file. Any help would be appreciated. 
```

Original comment by `loopyban...@gmail.com` on 4 Feb 2011 at 6:38

**Comment by GoogleCodeExporter** [comment]
```
i´m sorry to ask that but ... what is meant with "pair bluetooth(s)" ?
```

Original comment by `stefan.f...@gmail.com` on 4 Feb 2011 at 11:05

**Comment by GoogleCodeExporter** [comment]
```
Same problem here. All the tips don't work. Very frustrating =/
```

Original comment by `marius2...@gmail.com` on 14 Feb 2011 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
I solved the same problem by installing libbluetooth-dev on my Ubuntu 10.10 
64bit.
@comment12: Pairing bluetooth devices means that you allow the devices to use 
each other. Commonly this is done using a special mode and often a key which 
must be the same in both devices. Consult your device's documentation on how to 
do this.
```

Original comment by `fami...@tamm-tamm.de` on 24 Feb 2011 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
Just run the .jar file instead of .exe file to start the server application and 
bluetooth is gonna work properly!
```

Original comment by `francile...@gmail.com` on 24 Feb 2011 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
Got the Problem "bluetooth server is not running" with Windows 7 64
Debug says:

Native Library intelbth_x64 not available
Native Library bluecove_x64 not available
javax.bluetooth.BluetoothStateException: BlueCove libraries not available 
        at com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows(BlueCoveImpl
.java:896)
        at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:439)
        at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:65)
        at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1020)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.j
ava:1018)
        at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:
1011)
        at com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnec
tor.java:196)
        at com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.
java:162)
        at javax.microedition.io.Connector.open(Connector.java:83)
        at org.pierre.remotedroid.server.connection.PRemoteDroidServerBluetooth.
<init>(PRemoteDroidServerBluetooth.java:22)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDro
idServerApp.java:42)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroid
ServerApp.java:96)

Is it a problem with the default libs? Can i redirect to some 32 libs?
```

Original comment by `eriplin...@googlemail.com` on 8 Mar 2011 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
Got the problem "Bluetooth Server is not running" with Windows 7 64, too. Wifi 
workes great but bluetooth won't.

Couldn't wait longer till this bug is fixed. I tried another app from the 
android market and now bluetooth works fine. It's called "Unified Remote".

I will now use this program on an interim basis, till this problem is solved 
for me.


```

Original comment by `viktormi...@gmail.com` on 23 Jun 2011 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
This snippet worked fine the first few times, then just stopped.
Gives the native library not available error


 public static void main(String[] args) throws IOException {

            //create an instance of this class
            BluetoothDeviceDiscovery bluetoothDeviceDiscovery=new BluetoothDeviceDiscovery();

            //display local device address and name
            LocalDevice localDevice = LocalDevice.getLocalDevice();
            System.out.println("Address: "+localDevice.getBluetoothAddress());
            System.out.println("Name: "+localDevice.getFriendlyName());





```

Original comment by `kimkama...@gmail.com` on 15 Mar 2012 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
oh, i'm using the generic bluetooth adapter drivers on a usb dongle. Apparently 
that enables the winsock stack to work.
```

Original comment by `kimkama...@gmail.com` on 15 Mar 2012 at 1:17
