### ISSUE TITLE
bluetooth error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#71]
```
What steps will reproduce the problem?
1. java -jar /opt/PRemoteDroid-Server/PRemoteDroid-Server.jar
2. on android setup bluetooth connetction
3. no connection

all output

premotedroid 
BlueCove version 2.1.0 on bluez
java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:250)
    at org.pierre.remotedroid.protocol.action.PRemoteDroidAction.parse(PRemoteDroidAction.java:23)
    at org.pierre.remotedroid.protocol.PRemoteDroidConnection.receiveAction(PRemoteDroidConnection.java:30)
    at org.pierre.remotedroid.server.connection.PRemoteDroidServerConnection.run(PRemoteDroidServerConnection.java:73)
    at java.lang.Thread.run(Thread.java:662)


```

Original issue reported on code.google.com by `hellysmile@gmail.com` on 11 Nov 2010 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
by clicking bluetooth server, its says that server is running, but no 
connection(connection refused)
```

Original comment by `hellysmile@gmail.com` on 11 Nov 2010 at 5:13

**Comment by GoogleCodeExporter** [comment]
```
if i removes adapter - nothing changes, hot to see debug bluetotth output? or 
programm dont work in linux with blueman-applet ?
```

Original comment by `hellysmile@gmail.com` on 11 Nov 2010 at 5:15

**Comment by GoogleCodeExporter** [comment]
```
and when i tries to start it on second monitors i have these errors
$ DISPLAY=:0.1 premotedroid
java.awt.AWTException: TrayIcon couldn't be displayed.
    at sun.awt.X11.XTrayIconPeer.<init>(XTrayIconPeer.java:268)
    at sun.awt.X11.XToolkit.createTrayIcon(XToolkit.java:864)
    at java.awt.TrayIcon.addNotify(TrayIcon.java:669)
    at java.awt.SystemTray.add(SystemTray.java:237)
    at org.pierre.remotedroid.server.gui.PRemoteDroidServerTrayIcon.initTrayIcon(PRemoteDroidServerTrayIcon.java:189)
    at org.pierre.remotedroid.server.gui.PRemoteDroidServerTrayIcon.<init>(PRemoteDroidServerTrayIcon.java:41)
    at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDroidServerApp.java:29)
    at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroidServerApp.java:96)
```

Original comment by `hellysmile@gmail.com` on 12 Nov 2010 at 4:39
