### ISSUE TITLE
Bluetooth Server is not running

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#80]
```
When I try to start PRemoteDroid, it always says "Bluetooth server not 
running". 
Here is the output from running it in debug:

Native Library intelbth_x64 not available
Native Library bluecove_x64 not available
javax.bluetooth.BluetoothStateException: BlueCove libraries not available
        at com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows(BlueCoveImpl
.java:896)
        at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:439)
        at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:65)
        at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1020)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.j
ava:1018)
        at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:
1011)
        at com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnec
tor.java:196)
        at com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.
java:162)
        at javax.microedition.io.Connector.open(Connector.java:83)
        at org.pierre.remotedroid.server.connection.PRemoteDroidServerBluetooth.
<init>(PRemoteDroidServerBluetooth.java:22)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDro
idServerApp.java:42)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroid
ServerApp.java:96)

Any idea what to do?

TIA
Aze
```

Original issue reported on code.google.com by `azeph...@gmail.com` on 5 Dec 2010 at 10:42

**Comment by GoogleCodeExporter** [comment]
```
This has been described in Issues 30, 49, and 64. Get the 64-bit version of the 
bluecove jar, and you should be good to go.
```

Original comment by `alan.dav...@gmail.com` on 6 Dec 2010 at 4:54

**Comment by GoogleCodeExporter** [comment]
```
Could you tell me where to get that? It's not really clear and I think it would 
be a great help to everyone else as well if you could post a link to it. 

Regards
Aze
```

Original comment by `azeph...@gmail.com` on 6 Dec 2010 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
Okay, I found it myself, I downloaded them from here:

http://snapshot.bluecove.org/distribution/download/2.1.1-SNAPSHOT/2.1.1-SNAPSHOT
.62/

and replaced both bluecove-2.1.0.jar and bluecove-gpl-2.1.0.jar with those 
snapshots and it works now :-)
```

Original comment by `azeph...@gmail.com` on 6 Dec 2010 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
can anyone post a new link to these snapshots, cause this one is not working. I 
checked on the Svn and the distribution folder is empty! Thanks
```

Original comment by `lecs.dum...@gmail.com` on 29 May 2012 at 11:58
