### ISSUE TITLE
Server fails if window manager has no system tray

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tags07/premotedroid#86]
```
What steps will reproduce the problem?
Running a minimal window manager under Linux (ratpoison) fails

What is the expected output? What do you see instead?
Exception in thread "main" java.lang.UnsupportedOperationException
        at java.awt.TrayIcon.<init>(TrayIcon.java:112)
        at java.awt.TrayIcon.<init>(TrayIcon.java:136)
        at org.pierre.remotedroid.server.gui.PRemoteDroidServerTrayIcon.initTrayIcon(PRemoteDroidServerTrayIcon.java:184)
        at org.pierre.remotedroid.server.gui.PRemoteDroidServerTrayIcon.<init>(PRemoteDroidServerTrayIcon.java:41)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.<init>(PRemoteDroidServerApp.java:29)
        at org.pierre.remotedroid.server.PRemoteDroidServerApp.main(PRemoteDroidServerApp.java:96)


What version of the product are you using? On what operating system?
Gentoo linux, sun-jre-1.6

Please provide any additional information below.
I think a clause of the form
 if(SystemTray.isSupported()) {
    do as now
 }
 else
 {
   don't try and instantiate a gui, just use CLI only
 }
would sort out the problem but this is guess based on zero java experience



```

Original issue reported on code.google.com by `gb7...@gmail.com` on 12 Jan 2011 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
Problem is that PRemoteDroidServer is dependent on a running X server.

It can't run in console mode unless these clever boys can switch the key 
commands between X and the console. It's a huge effort with very little value 
added to the application.

See the code 

https://github.com/dpavlin/premotedroid-server-perl

Basically all this app is doing is to pipe instructions from the network to X 
via xdotool
```

Original comment by `shafs...@gmail.com` on 7 Mar 2011 at 10:20
